### ISSUE TITLE
Poor read performance.

### ISSUE THREAD

**Issue by stefan-guggisberg** [bigeasy/locket#138]
i am working on an mvcc hierarchical store implementation supporting structured, semi-structured and unstructured data using leveldown for persistence.

i've experimented with locket but hit strange performance issues.

i populated the db with ~200k entries. keys are binary, 20 bytes (sha1 of value). values are binary, a couple of hundreds to a few thousand bytes each.

the entries make up a mvcc git-like tree model.

populating the db was surprisingly fast, i read the entries from a leveldb instance and wrote them in batches of 10k entries. write performance was ~0.5ms/entry.

reading however is very slow, on average **~300ms/entry** for random keys.

i store a special entry with if an zero id ([ 0,0,0, .. ]). reading this special entry takes **4-6 seconds**...

when i run the same code with leveldown instead of locket i get consistent 0.5ms/entry for reading.

i am using default options for locket. reading and writing is done with {asBuffer: true}.

locket is a great project and i'd love to be an early adopter. is there anything i can tweak in order to get better read performance?

i'd be happy to share the locket files (~40mb zip) if it helps.

**UPDATE**: Performance Task List

- [ ] Implement a simplified record structure so that the record writing does not look so terrible and checksums are pluggable.
- [x] Move the balance operations out of `Balancer` and into `Sheaf` in Strata.
- [x] Create JSPerf style benchmarks for Cadence, compare to other control flow libraries to see if it much slower.
- [ ] Strip Strata of anything that is a shim.
- [ ] Create a profiler library to wrap Strata functions.
- [x] Create a benchmark directory for Strata in Locket.
- [ ] Begin caching aggressively.

**Comment by bigeasy** [comment]
Performance has improved dramatically. Reads are still slowish, but not dreadful. Writes, for your basic case are fast. Using just Strata, performance is an order of magnitude away from LevelDB on write, and three times slower on read. This is down from two orders of magnitude.

The `-d` switch below means to use LevelDB.

```
 % node locket/benchmark/load.js  -d
insert: 46ms, gather: 66ms
 % node locket/benchmark/load.js
insert: 510ms, gather: 1149ms
 % node strata/benchmark/load.js
insert: 261ms, gather: 133ms
```

There is still room for improvement in both Locket and it's basis, Strata. There is a lot of room for improvement in Locket read times.

**Comment by bigeasy** [comment]
And so, I'm going to close this when I get the gather benchmark closers to 200ms.
